FROM rust:latest as builder

WORKDIR /usr/src/cria
RUN git clone https://github.com/AmineDiro/cria .
RUN cargo build --release 
RUN apt-get update -y && apt-get install -y wget
RUN wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_0.bin -O /model.bin

FROM debian:stable-slim

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /model.bin /app/model.bin
COPY --from=builder /usr/src/cria/target/release/cria /usr/local/bin/cria
CMD ["cria","--model","/app/model.bin"]