name: Build Images
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Log in to the Github Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker file
      run: |
        docker build -t ghcr.io/bionic-gpt/llama-3.2-3b:latest -t bionic-gpt/llama-3.2-3b:latest -f Dockerfile.llama3.2-3b.cpu .
        docker push ghcr.io/bionic-gpt/llama-3.2-3b:latest

        docker build -t ghcr.io/bionic-gpt/llama-3-8b-chat:latest -t bionic-gpt/llama-3-8b-chat:latest -f Dockerfile.llama-3-8b-chat .
        docker push ghcr.io/bionic-gpt/llama-3-8b-chat:latest

        docker build -t ghcr.io/bionic-gpt/embeddings:latest -t bionic-gpt/embeddings:latest -f Dockerfile.embeddings .
        docker push ghcr.io/bionic-gpt/embeddings:latest

    - name: Semantic Release
      run: | 
        npm i -D @semantic-release/exec
        npm i -D @semantic-release-plus/docker
        npm i -D @semantic-release/git
        npx semantic-release
