name: Build Images
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Log in to the Github Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Build and push for ARM and AMD
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile.7b.cpu
        platforms: linux/amd64,linux/arm64
        push: true
        tags: bionic-gpt/llama-2-7b-chat:latest

    - name: Semantic Release
      run: | 
        npm i -D @semantic-release/exec
        npm i -D @semantic-release-plus/docker
        npm i -D @semantic-release/git
        npx semantic-release