name: Build Inages
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Log in to the Github Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker file
      run: |
        docker build -t ghcr.io/docllama/llama-2-7b-instruct -f Dockerfile.7b.cpu .